const fs = require("fs");
const path = require("path");
const os = require("os");
const {
  BACKLOG_FILENAME,
  LEGACY_BACKLOG_FILENAME,
  ensureBacklogFile,
  appendCommit,
  appendSession,
  getBacklogPath,
} = require("../src/backlogFile");

describe("backlogFile", () => {
  let tempDir;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "pm-backlog-test-"));
  });

  afterEach(() => {
    try {
      fs.rmSync(tempDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });

  it("creates BACKLOG.md with header if file does not exist", () => {
    const filePath = ensureBacklogFile(tempDir);
    expect(filePath).toBe(path.join(tempDir, BACKLOG_FILENAME));
    expect(fs.existsSync(filePath)).toBe(true);

    const content = fs.readFileSync(filePath, "utf8");
    expect(content).toContain("# Project Backlog & Activity Log");
    expect(content).toContain("Auto-generated by **PM Connect**");
  });

  it("preserves existing PM-CONNECT-BACKLOG.md if legacy file exists", () => {
    const legacyPath = path.join(tempDir, LEGACY_BACKLOG_FILENAME);
    fs.writeFileSync(legacyPath, "# Legacy Backlog\n", "utf8");

    const filePath = ensureBacklogFile(tempDir);
    expect(filePath).toBe(legacyPath);
  });

  it("appends a commit with SHA, message, and files list", () => {
    appendCommit(tempDir, {
      commitSha: "abc1234567890",
      commitMessage: "Add user profile settings\n\nInclude avatar upload and bio fields",
      filesChanged: ["src/profile.js", "src/avatar.png"],
      timestamp: "2026-09-18T10:30:00.000Z",
    });

    const filePath = path.join(tempDir, BACKLOG_FILENAME);
    const content = fs.readFileSync(filePath, "utf8");

    expect(content).toContain("## 2026-09-18");
    expect(content).toContain("Commit `[abc1234]` — **\"Add user profile settings\"**");
    expect(content).toContain("**Comment:** Include avatar upload and bio fields");
    expect(content).toContain("Changed Files (2):");
    expect(content).toContain("`src/profile.js`");
    expect(content).toContain("`src/avatar.png`");
  });

  it("appends an active coding session with duration and files", () => {
    appendSession(tempDir, {
      startTime: "14:00",
      endTime: "14:45",
      durationMinutes: 45,
      filesChanged: ["src/index.js", "src/styles.css"],
    });

    const filePath = path.join(tempDir, BACKLOG_FILENAME);
    const content = fs.readFileSync(filePath, "utf8");

    expect(content).toContain("Active Coding Session (**45 min**)");
    expect(content).toContain("Files Worked On (2):");
    expect(content).toContain("`src/index.js`");
    expect(content).toContain("`src/styles.css`");
  });

  it("updates an ongoing coding session in-place instead of creating duplicates", () => {
    const { recordOrUpdateSession } = require("../src/backlogFile");

    recordOrUpdateSession(tempDir, {
      startTime: "14:00",
      endTime: "14:05",
      durationMinutes: 5,
      filesChanged: ["src/index.js"],
    });

    const filePath = path.join(tempDir, BACKLOG_FILENAME);
    let content = fs.readFileSync(filePath, "utf8");
    expect(content).toContain("Active Coding Session (**5 min**)");
    expect(content).toContain("`src/index.js`");

    recordOrUpdateSession(tempDir, {
      startTime: "14:00",
      endTime: "14:20",
      durationMinutes: 20,
      filesChanged: ["src/index.js", "src/utils.js"],
    });

    content = fs.readFileSync(filePath, "utf8");
    const sessionMatches = (content.match(/Active Coding Session/g) || []).length;
    expect(sessionMatches).toBe(1);
    expect(content).toContain("14:00 – 14:20");
    expect(content).toContain("Active Coding Session (**20 min**)");
    expect(content).toContain("`src/utils.js`");
  });

  it("appends multiple commits and sessions under the same date without duplicating date header", () => {
    const folderObj = { uri: { fsPath: tempDir } };

    appendCommit(folderObj, {
      commitSha: "1111111",
      commitMessage: "First commit",
      filesChanged: ["file1.txt"],
      timestamp: "2026-09-18T09:00:00.000Z",
    });

    appendSession(folderObj, {
      startTime: "09:30",
      endTime: "10:15",
      durationMinutes: 45,
      filesChanged: ["file2.txt"],
    });

    appendCommit(folderObj, {
      commitSha: "2222222",
      commitMessage: "Second commit",
      filesChanged: ["file3.txt"],
      timestamp: "2026-09-18T11:00:00.000Z",
    });

    const filePath = path.join(tempDir, BACKLOG_FILENAME);
    const content = fs.readFileSync(filePath, "utf8");

    // Count occurrences of "## 2026-09-18"
    const occurrences = (content.match(/## 2026-09-18/g) || []).length;
    expect(occurrences).toBe(1);

    expect(content).toContain("First commit");
    expect(content).toContain("Active Coding Session (**45 min**)");
    expect(content).toContain("Second commit");
  });

  it("handles empty changed files gracefully", () => {
    appendCommit(tempDir, {
      commitSha: "3333333",
      commitMessage: "Initial empty commit",
      filesChanged: [],
      timestamp: "2026-09-18T12:00:00.000Z",
    });

    const filePath = path.join(tempDir, BACKLOG_FILENAME);
    const content = fs.readFileSync(filePath, "utf8");
    expect(content).toContain("*(none detected)*");
  });

  it("strictly isolates logs between different project folders", () => {
    const projectADir = fs.mkdtempSync(path.join(os.tmpdir(), "pm-project-A-"));
    const projectBDir = fs.mkdtempSync(path.join(os.tmpdir(), "pm-project-B-"));

    try {
      appendCommit(projectADir, {
        commitSha: "aaaaaaa",
        commitMessage: "Feature A commit",
        filesChanged: ["src/featureA.js"],
      });

      appendSession(projectADir, {
        startTime: "10:00",
        endTime: "10:30",
        durationMinutes: 30,
        filesChanged: ["src/featureA.js"],
      });

      appendCommit(projectBDir, {
        commitSha: "bbbbbbb",
        commitMessage: "Feature B commit",
        filesChanged: ["src/featureB.js"],
      });

      appendSession(projectBDir, {
        startTime: "11:00",
        endTime: "11:45",
        durationMinutes: 45,
        filesChanged: ["src/featureB.js"],
      });

      const contentA = fs.readFileSync(path.join(projectADir, BACKLOG_FILENAME), "utf8");
      const contentB = fs.readFileSync(path.join(projectBDir, BACKLOG_FILENAME), "utf8");

      // Project A must ONLY have Feature A logs
      expect(contentA).toContain("Feature A commit");
      expect(contentA).toContain("src/featureA.js");
      expect(contentA).not.toContain("Feature B commit");
      expect(contentA).not.toContain("src/featureB.js");

      // Project B must ONLY have Feature B logs
      expect(contentB).toContain("Feature B commit");
      expect(contentB).toContain("src/featureB.js");
      expect(contentB).not.toContain("Feature A commit");
      expect(contentB).not.toContain("src/featureA.js");
    } finally {
      fs.rmSync(projectADir, { recursive: true, force: true });
      fs.rmSync(projectBDir, { recursive: true, force: true });
    }
  });

  describe("calculateMinutesBetween and duration accuracy", () => {
    const { calculateMinutesBetween, getTimeSummaryFromBacklog, recordOrUpdateSession, getLocalDateString } = require("../src/backlogFile");

    it("calculates accurate minutes between times including seconds and midnight crossing", () => {
      expect(calculateMinutesBetween("10:31:38", "11:49:06")).toBe(77);
      expect(calculateMinutesBetween("14:00", "14:45")).toBe(45);
      expect(calculateMinutesBetween("14:00", "14:05")).toBe(5);
      expect(calculateMinutesBetween("23:50", "00:20")).toBe(30);
      expect(calculateMinutesBetween("10:00", "10:00")).toBe(0);
      expect(calculateMinutesBetween("", "10:00")).toBe(0);
    });

    it("prevents developer under-counting by calculating true duration when 1 min is erroneously passed", () => {
      recordOrUpdateSession(tempDir, {
        startTime: "10:31:38",
        endTime: "11:49:06",
        durationMinutes: 1, // bug simulation
        filesChanged: ["README.md", "frontend"],
      });

      const filePath = path.join(tempDir, BACKLOG_FILENAME);
      const content = fs.readFileSync(filePath, "utf8");
      expect(content).toContain("10:31:38 – 11:49:06");
      expect(content).toContain("Active Coding Session (**77 min**)");
      expect(content).not.toContain("Active Coding Session (**1 min**)");
    });

    it("auto-reconciles legacy 1-min bug entries when parsing time summary from BACKLOG.md", () => {
      const today = getLocalDateString();
      const filePath = path.join(tempDir, BACKLOG_FILENAME);
      const legacyContent = `# Backlog\n\n## ${today}\n\n- **10:31:38 – 11:49:06** ⏱️ Active Coding Session (**1 min**)\n  - 📁 **Files Worked On (2):**\n    - \`README.md\`\n    - \`frontend\`\n`;
      fs.writeFileSync(filePath, legacyContent, "utf8");

      const summary = getTimeSummaryFromBacklog(tempDir);
      expect(summary.todayMinutes).toBe(77);
      expect(summary.todayHours).toBe((77 / 60).toFixed(2));
    });
  });
});

