const fs = require("fs");
const path = require("path");

const BACKLOG_FILENAME = "BACKLOG.md";
const LEGACY_BACKLOG_FILENAME = "PM-CONNECT-BACKLOG.md";

const HEADER =
  "# Project Backlog & Activity Log\n\n" +
  "> Auto-generated by **PM Connect**. All git commits, comments, modified files/folders, " +
  "and active coding sessions are automatically recorded here date-wise.\n\n" +
  "---\n";

function getLocalDateString(d = new Date()) {
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function getLocalTimeString(d = new Date()) {
  const hr = String(d.getHours()).padStart(2, "0");
  const min = String(d.getMinutes()).padStart(2, "0");
  return `${hr}:${min}`;
}

function getFolderPath(folder) {
  if (!folder) return null;
  if (typeof folder === "string") return folder;
  if (folder.uri?.fsPath) return folder.uri.fsPath;
  if (folder.fsPath) return folder.fsPath;
  return null;
}

function getBacklogPath(folder) {
  const dir = getFolderPath(folder);
  if (!dir) return null;
  // Check if legacy filename already exists in this folder
  const legacyPath = path.join(dir, LEGACY_BACKLOG_FILENAME);
  if (fs.existsSync(legacyPath)) {
    return legacyPath;
  }
  return path.join(dir, BACKLOG_FILENAME);
}

/**
 * Creates the backlog file inside the project workspace folder if it doesn't already exist.
 */
function ensureBacklogFile(folder) {
  try {
    const filePath = getBacklogPath(folder);
    if (!filePath) return null;
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, HEADER + "\n", "utf8");
    }
    return filePath;
  } catch {
    // Silent — read-only workspace or permissions should never crash extension
    return null;
  }
}

/**
 * Appends a block of text under the specified date's section.
 * Creates the date section if it doesn't already exist.
 */
function appendToDateSection(folder, date, block) {
  try {
    const filePath = ensureBacklogFile(folder);
    if (!filePath) return;

    const dateHeader = `## ${date}`;
    let content = fs.readFileSync(filePath, "utf8");

    if (!content.includes(dateHeader)) {
      // New date section
      const addition = `\n${dateHeader}\n\n${block}\n`;
      fs.appendFileSync(filePath, addition, "utf8");
    } else {
      // Find the date section and append at the end of this date's entries (before the next '## ' or EOF)
      const dateIdx = content.indexOf(dateHeader);
      const nextHeaderIdx = content.indexOf("\n## ", dateIdx + dateHeader.length);

      if (nextHeaderIdx === -1) {
        // This is already the last section in the file
        const addition = content.endsWith("\n") ? `${block}\n` : `\n${block}\n`;
        fs.appendFileSync(filePath, addition, "utf8");
      } else {
        // Insert right before the next date header
        const before = content.slice(0, nextHeaderIdx);
        const after = content.slice(nextHeaderIdx);
        const newContent = `${before.trimEnd()}\n\n${block}\n${after}`;
        fs.writeFileSync(filePath, newContent, "utf8");
      }
    }
  } catch {
    // Silent — backlog writing should never crash tracking
  }
}

/**
 * Records a detected Git commit into the project's backlog file.
 */
function appendCommit(folder, { commitSha, commitMessage, filesChanged = [], timestamp = null }) {
  const d = timestamp ? new Date(timestamp) : new Date();
  const date = getLocalDateString(d);
  const time = getLocalTimeString(d);
  const shortSha = (commitSha || "").slice(0, 7);

  const lines = (commitMessage || "Git commit").trim().split("\n");
  const subject = lines[0] || "Git commit";
  const bodyComment = lines.slice(1).join("\n").trim();

  let block = `- **${time}** 🌿 Commit \`[${shortSha}]\` — **"${subject}"**`;
  if (bodyComment) {
    block += `\n  - **Comment:** ${bodyComment.replace(/\n/g, " ")}`;
  }

  if (Array.isArray(filesChanged) && filesChanged.length > 0) {
    block += `\n  - 📁 **Changed Files (${filesChanged.length}):**`;
    for (const file of filesChanged) {
      block += `\n    - \`${file}\``;
    }
  } else {
    block += `\n  - 📁 **Changed Files:** *(none detected)*`;
  }

  appendToDateSection(folder, date, block);
}

function parseSec(str) {
  if (!str) return null;
  const parts = String(str).trim().split(":").map((p) => parseInt(p, 10));
  if (parts.some(isNaN) || parts.length < 2) return null;
  const [h, m, s = 0] = parts;
  return h * 3600 + m * 60 + s;
}

/**
 * Calculates elapsed minutes between two HH:MM or HH:MM:SS time strings.
 * Handles overnight rollovers gracefully.
 */
function calculateMinutesBetween(startTimeStr, endTimeStr) {
  if (!startTimeStr || !endTimeStr) return 0;
  const s1 = parseSec(startTimeStr);
  const s2 = parseSec(endTimeStr);
  if (s1 === null || s2 === null) return 0;
  let diffSec = s2 - s1;
  if (diffSec < 0) diffSec += 24 * 3600; // overnight crossing
  return Math.round(diffSec / 60);
}

/**
 * Records or updates an active coding session into the project's backlog file.
 * If a session starting with startTime already exists under today's date, it updates in-place.
 * Otherwise, it appends a new session block.
 */
function recordOrUpdateSession(folder, { startTime, endTime, durationMinutes, filesChanged = [] }) {
  try {
    const filePath = ensureBacklogFile(folder);
    if (!filePath) return;

    const date = getLocalDateString();
    // The block always shows "start – end" right next to the minute count,
    // so the count must equal that same span — otherwise "10:46 – 10:54 (6
    // min)" reads as a contradiction even though it's a real 7-8 min gap.
    const s1 = parseSec(startTime);
    const s2 = parseSec(endTime);
    let duration = 1;
    if (s1 !== null && s2 !== null) {
      let diffSec = s2 - s1;
      if (diffSec < 0) diffSec += 24 * 3600;
      const wallClockMin = Math.round(diffSec / 60);
      duration = wallClockMin > 0 ? wallClockMin : 1;
    } else {
      duration = Math.max(1, parseInt(durationMinutes, 10) || 1);
    }
    const dateHeader = `## ${date}`;

    let block = `- **${startTime} – ${endTime}** ⏱️ Active Coding Session (**${duration} min**)`;
    if (Array.isArray(filesChanged) && filesChanged.length > 0) {
      const validFiles = filesChanged.filter((f) => {
        if (!f) return false;
        const clean = String(f).replace(/\\/g, "/").toLowerCase();
        return (
          clean !== ".git" &&
          !clean.startsWith(".git/") &&
          !clean.includes("/.git/") &&
          clean !== "node_modules" &&
          !clean.startsWith("node_modules/") &&
          !clean.includes("/node_modules/") &&
          !clean.endsWith("backlog.md") &&
          !clean.endsWith(".tmp")
        );
      });
      if (validFiles.length > 0) {
        block += `\n  - 📁 **Files Worked On (${validFiles.length}):**`;
        for (const file of validFiles) {
          block += `\n    - \`${file}\``;
        }
      }
    }

    let content = fs.readFileSync(filePath, "utf8");

    if (!content.includes(dateHeader)) {
      const addition = `\n${dateHeader}\n\n${block}\n`;
      fs.appendFileSync(filePath, addition, "utf8");
      return;
    }

    const dateIdx = content.indexOf(dateHeader);
    const afterDate = content.slice(dateIdx + dateHeader.length);
    const nextHeaderMatch = afterDate.search(/\n## /);
    const sectionEndIdx = nextHeaderMatch === -1 ? content.length : dateIdx + dateHeader.length + nextHeaderMatch;

    const sectionContent = content.slice(dateIdx, sectionEndIdx);
    let sessionPrefix = `- **${startTime} – `;
    let sessionIdx = sectionContent.indexOf(sessionPrefix);
    if (sessionIdx === -1) {
      sessionPrefix = `- **${startTime} - `;
      sessionIdx = sectionContent.indexOf(sessionPrefix);
    }

    if (sessionIdx !== -1) {
      const absStart = dateIdx + sessionIdx;
      const afterMatch = content.slice(absStart + sessionPrefix.length);
      const nextItemMatch = afterMatch.search(/\n- \*\*/);
      let absEnd;
      if (nextItemMatch === -1 || absStart + sessionPrefix.length + nextItemMatch > sectionEndIdx) {
        absEnd = sectionEndIdx;
      } else {
        absEnd = absStart + sessionPrefix.length + nextItemMatch;
      }

      const before = content.slice(0, absStart).trimEnd();
      const after = content.slice(absEnd).trimStart();
      const newContent = `${before}\n\n${block}${after ? `\n\n${after}` : "\n"}`;
      fs.writeFileSync(filePath, newContent, "utf8");
    } else {
      appendToDateSection(folder, date, block);
    }
  } catch {
    // Silent — backlog writing should never crash tracking
  }
}

function appendSession(folder, opts) {
  recordOrUpdateSession(folder, opts);
}

/**
 * Accurately parses BACKLOG.md to calculate:
 * - todayMinutes: Total minutes active today
 * - totalMinutes: Cumulative minutes from the very start until today
 * - dateBreakdown: Array of { date, minutes, hours }
 * - firstDate: First recorded date
 */
function getTimeSummaryFromBacklog(folder) {
  try {
    const filePath = getBacklogPath(folder);
    if (!filePath || !fs.existsSync(filePath)) {
      return { todayMinutes: 0, totalMinutes: 0, todayHours: "0.00", totalHours: "0.00", dateBreakdown: [], firstDate: null };
    }

    const content = fs.readFileSync(filePath, "utf8");
    const lines = content.split("\n");
    const today = getLocalDateString();
    let currentDate = null;
    const dateTotals = {};
    const dateFiles = {};

    for (const line of lines) {
      const dateMatch = line.match(/^##\s+(\d{4}-\d{2}-\d{2})/);
      if (dateMatch) {
        currentDate = dateMatch[1];
        if (dateTotals[currentDate] === undefined) {
          dateTotals[currentDate] = 0;
          dateFiles[currentDate] = new Set();
        }
        continue;
      }

      // Match files worked on like: - `src/filename.ext`
      const fileMatch = line.match(/^\s*-\s*`([^`]+)`/);
      if (fileMatch && currentDate) {
        if (!dateFiles[currentDate]) dateFiles[currentDate] = new Set();
        dateFiles[currentDate].add(fileMatch[1].trim());
      }

      // Match sessions like: Active Coding Session (**4 min**) or (**1 hr 20 min**)
      const sessionMatch = line.match(/Active Coding Session\s*\(\*\*([^*]+)\*\*\)/i);
      if (sessionMatch && currentDate) {
        const durStr = sessionMatch[1].trim();
        let minutes = 0;
        const hrMatch = durStr.match(/(\d+)\s*(?:hr|hour)s?/i);
        const minMatch = durStr.match(/(\d+)\s*min/i);
        if (hrMatch) minutes += parseInt(hrMatch[1], 10) * 60;
        if (minMatch) minutes += parseInt(minMatch[1], 10);
        if (!hrMatch && !minMatch) {
          const justNum = parseInt(durStr, 10);
          if (!isNaN(justNum)) minutes += justNum;
        }

        // Safety reconciliation: if logged minutes is 1, but the line's time span (startTime - endTime)
        // is clearly larger (e.g. 10:31:38 to 11:49:06 is 77 min), count the full accurate time!
        const rangeMatch = line.match(/\*\*(\d{1,2}:\d{2}(?::\d{2})?)\s*[\u2013-]\s*(\d{1,2}:\d{2}(?::\d{2})?)\*\*/);
        if (rangeMatch) {
          const spanMin = calculateMinutesBetween(rangeMatch[1], rangeMatch[2]);
          if (spanMin > 1 && minutes <= 1) {
            minutes = spanMin;
          }
        }

        dateTotals[currentDate] += minutes;
      }
    }

    const dates = Object.keys(dateTotals).sort();
    const dateBreakdown = dates.map((d) => ({
      date: d,
      minutes: dateTotals[d],
      hours: (dateTotals[d] / 60).toFixed(2),
      files: Array.from(dateFiles[d] || []).slice(0, 30),
    }));

    const todayMinutes = dateTotals[today] || 0;
    const totalMinutes = dateBreakdown.reduce((sum, item) => sum + item.minutes, 0);
    const firstDate = dates.length > 0 ? dates[0] : null;

    return {
      todayDate: today,
      todayMinutes,
      totalMinutes,
      todayHours: (todayMinutes / 60).toFixed(2),
      totalHours: (totalMinutes / 60).toFixed(2),
      dateBreakdown,
      firstDate,
    };
  } catch {
    return { todayMinutes: 0, totalMinutes: 0, todayHours: "0.00", totalHours: "0.00", dateBreakdown: [], firstDate: null };
  }
}

module.exports = {
  BACKLOG_FILENAME,
  LEGACY_BACKLOG_FILENAME,
  getBacklogPath,
  ensureBacklogFile,
  appendCommit,
  appendSession,
  recordOrUpdateSession,
  getTimeSummaryFromBacklog,
  getLocalDateString,
  calculateMinutesBetween,
};
