const fs = require("fs");
const path = require("path");

const BACKLOG_FILENAME = "BACKLOG.md";
const LEGACY_BACKLOG_FILENAME = "PM-CONNECT-BACKLOG.md";

const HEADER =
  "# Project Backlog & Activity Log\n\n" +
  "> Auto-generated by **PM Connect**. All git commits, comments, modified files/folders, " +
  "and active coding sessions are automatically recorded here date-wise.\n\n" +
  "---\n";

function getLocalDateString(d = new Date()) {
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function getLocalTimeString(d = new Date()) {
  const hr = String(d.getHours()).padStart(2, "0");
  const min = String(d.getMinutes()).padStart(2, "0");
  return `${hr}:${min}`;
}

function getFolderPath(folder) {
  if (!folder) return null;
  if (typeof folder === "string") return folder;
  if (folder.uri?.fsPath) return folder.uri.fsPath;
  if (folder.fsPath) return folder.fsPath;
  return null;
}

function getBacklogPath(folder) {
  const dir = getFolderPath(folder);
  if (!dir) return null;
  // Check if legacy filename already exists in this folder
  const legacyPath = path.join(dir, LEGACY_BACKLOG_FILENAME);
  if (fs.existsSync(legacyPath)) {
    return legacyPath;
  }
  return path.join(dir, BACKLOG_FILENAME);
}

/**
 * Creates the backlog file inside the project workspace folder if it doesn't already exist.
 */
function ensureBacklogFile(folder) {
  try {
    const filePath = getBacklogPath(folder);
    if (!filePath) return null;
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, HEADER + "\n", "utf8");
    }
    return filePath;
  } catch {
    // Silent — read-only workspace or permissions should never crash extension
    return null;
  }
}

/**
 * Appends a block of text under the specified date's section.
 * Creates the date section if it doesn't already exist.
 */
function appendToDateSection(folder, date, block) {
  try {
    const filePath = ensureBacklogFile(folder);
    if (!filePath) return;

    const dateHeader = `## ${date}`;
    let content = fs.readFileSync(filePath, "utf8");

    if (!content.includes(dateHeader)) {
      // New date section
      const addition = `\n${dateHeader}\n\n${block}\n`;
      fs.appendFileSync(filePath, addition, "utf8");
    } else {
      // Find the date section and append at the end of this date's entries (before the next '## ' or EOF)
      const dateIdx = content.indexOf(dateHeader);
      const nextHeaderIdx = content.indexOf("\n## ", dateIdx + dateHeader.length);

      if (nextHeaderIdx === -1) {
        // This is already the last section in the file
        const addition = content.endsWith("\n") ? `${block}\n` : `\n${block}\n`;
        fs.appendFileSync(filePath, addition, "utf8");
      } else {
        // Insert right before the next date header
        const before = content.slice(0, nextHeaderIdx);
        const after = content.slice(nextHeaderIdx);
        const newContent = `${before.trimEnd()}\n\n${block}\n${after}`;
        fs.writeFileSync(filePath, newContent, "utf8");
      }
    }
  } catch {
    // Silent — backlog writing should never crash tracking
  }
}

/**
 * Records a detected Git commit into the project's backlog file.
 */
function appendCommit(folder, { commitSha, commitMessage, filesChanged = [], timestamp = null }) {
  const d = timestamp ? new Date(timestamp) : new Date();
  const date = getLocalDateString(d);
  const time = getLocalTimeString(d);
  const shortSha = (commitSha || "").slice(0, 7);

  const lines = (commitMessage || "Git commit").trim().split("\n");
  const subject = lines[0] || "Git commit";
  const bodyComment = lines.slice(1).join("\n").trim();

  let block = `- **${time}** 🌿 Commit \`[${shortSha}]\` — **"${subject}"**`;
  if (bodyComment) {
    block += `\n  - **Comment:** ${bodyComment.replace(/\n/g, " ")}`;
  }

  if (Array.isArray(filesChanged) && filesChanged.length > 0) {
    block += `\n  - 📁 **Changed Files (${filesChanged.length}):**`;
    for (const file of filesChanged) {
      block += `\n    - \`${file}\``;
    }
  } else {
    block += `\n  - 📁 **Changed Files:** *(none detected)*`;
  }

  appendToDateSection(folder, date, block);
}

/**
 * Records or updates an active coding session into the project's backlog file.
 * If a session starting with startTime already exists under today's date, it updates in-place.
 * Otherwise, it appends a new session block.
 */
function recordOrUpdateSession(folder, { startTime, endTime, durationMinutes, filesChanged = [] }) {
  try {
    const filePath = ensureBacklogFile(folder);
    if (!filePath) return;

    const date = getLocalDateString();
    const duration = Math.max(1, parseInt(durationMinutes, 10) || 1);
    const dateHeader = `## ${date}`;

    let block = `- **${startTime} – ${endTime}** ⏱️ Active Coding Session (**${duration} min**)`;
    if (Array.isArray(filesChanged) && filesChanged.length > 0) {
      block += `\n  - 📁 **Files Worked On (${filesChanged.length}):**`;
      for (const file of filesChanged) {
        block += `\n    - \`${file}\``;
      }
    }

    let content = fs.readFileSync(filePath, "utf8");

    if (!content.includes(dateHeader)) {
      const addition = `\n${dateHeader}\n\n${block}\n`;
      fs.appendFileSync(filePath, addition, "utf8");
      return;
    }

    const dateIdx = content.indexOf(dateHeader);
    const afterDate = content.slice(dateIdx + dateHeader.length);
    const nextHeaderMatch = afterDate.search(/\n## /);
    const sectionEndIdx = nextHeaderMatch === -1 ? content.length : dateIdx + dateHeader.length + nextHeaderMatch;

    const sectionContent = content.slice(dateIdx, sectionEndIdx);
    const sessionPrefix = `- **${startTime} – `;
    const sessionIdx = sectionContent.indexOf(sessionPrefix);

    if (sessionIdx !== -1) {
      const absStart = dateIdx + sessionIdx;
      const afterMatch = content.slice(absStart + sessionPrefix.length);
      const nextItemMatch = afterMatch.search(/\n- \*\*/);
      let absEnd;
      if (nextItemMatch === -1 || absStart + sessionPrefix.length + nextItemMatch > sectionEndIdx) {
        absEnd = sectionEndIdx;
      } else {
        absEnd = absStart + sessionPrefix.length + nextItemMatch;
      }

      const before = content.slice(0, absStart).trimEnd();
      const after = content.slice(absEnd).trimStart();
      const newContent = `${before}\n\n${block}${after ? `\n\n${after}` : "\n"}`;
      fs.writeFileSync(filePath, newContent, "utf8");
    } else {
      appendToDateSection(folder, date, block);
    }
  } catch {
    // Silent — backlog writing should never crash tracking
  }
}

function appendSession(folder, opts) {
  recordOrUpdateSession(folder, opts);
}

module.exports = {
  BACKLOG_FILENAME,
  LEGACY_BACKLOG_FILENAME,
  getBacklogPath,
  ensureBacklogFile,
  appendCommit,
  appendSession,
  recordOrUpdateSession,
};
